#######################
# Theme Customization #
#######################

title: Pagan                                # used in <title> tag & site header
author: Pagan                               # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Blog pribadi yang berisi kumpulan tulisan random,
  Berasal dari pengalaman yang pernah saya alami.
slogan: Pratama                             # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: https://developer.rfproduction.com     # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Archives
    url: /archives
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/roganro
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: pagan_pratama       # you know, to protect you from bots. (handle and domain
    domain: yahoo.co.id # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

#################
# Site Settings #
#################

incremental: true

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

paginate_multiple:
  - paginate: 10
    paginate_path: '/page/:num'
    sub_dir: '/'
  - paginate: 10
    paginate_path: '/archives/page/:num'
    sub_dir: '/archives'

# Sass/SCSS settings
sass:
  sass_dir: _assets/css

# Collection Defaults
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    permalink: /:categories/p-:y_day/:title
    comments: true
- scope:
    type: tag
  values:
    layout: listing
- scope:
    type: category
  values:
    layout: listing
- scope:
    path: _posts/archives
    type: posts
  values:
    layout: post
    permalink: /archives/:categories/p-:y_day/:title
    comments: false

# File Handling
include: [archives]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json, TODO.md, .travis.yml, bin/*, circle.yml, yarn.lock]